"""One-shot Colab environment setup.

The failure this exists to prevent: Colab ships numpy, Pillow, scipy, OpenCV and
torch already compiled against each other, and every separate `pip install` is a
separate resolution that is free to move one of them to satisfy some new
package's pin. A partly applied downgrade leaves a package's Python files and its
compiled extension on different versions, and then everything linked against it
fails with an error naming the wrong culprit - a broken numpy reports itself as
"rembg is not installed".

So: read the versions Colab shipped, write them to a constraints file, and do the
whole installation as one transaction bounded by it. Anything that genuinely
cannot live with that baseline now fails loudly at install time, naming itself,
instead of quietly breaking an unrelated import twenty minutes later.

    python tools/colab_setup.py                      # both backends
    python tools/colab_setup.py --backend triposr
    python tools/colab_setup.py --cache-dir /content/drive/MyDrive/p3d-pip-cache

Model weights are not downloaded here; they arrive on first use.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONSTRAINTS = PROJECT_ROOT / "constraints-colab.txt"

# Compiled against each other in the Colab image. Pinned to whatever is already
# installed so no later resolution can move them. torch is here because pulling a
# different build is a multi-gigabyte download that also loses CUDA support.
BASELINE = (
    "numpy",
    "pillow",
    "scipy",
    "numba",
    "llvmlite",
    "opencv-python",
    "opencv-python-headless",
    "opencv-contrib-python",
    "torch",
    "torchvision",
    "torchaudio",
)

CORE = ("rembg", "onnxruntime", "gradio", "trimesh", "pytest")

BACKEND_PACKAGES = {
    "triposr": (
        "omegaconf",
        "einops",
        "jaxtyping",
        "transformers",
        "safetensors",
        "huggingface-hub",
        "imageio",
        "xatlas",
        "pygltflib",
        # Provides the CPU marching cubes the adapter falls back to when
        # torchmcubes, a CUDA extension, will not build.
        "scikit-image",
    ),
    "hunyuan3d": (
        "transformers",
        "diffusers",
        "accelerate",
        "safetensors",
        "omegaconf",
        "einops",
        "scikit-image",
        # hy3dshape imports pymeshlab, and the repo does not declare it anywhere
        # the notebook picks up.
        "pymeshlab",
        "pygltflib",
        "xatlas",
        "pytorch-lightning",
        "torchmetrics",
        "timm",
        "torchdiffeq",
        "huggingface-hub",
    ),
}

UNIDEPTH_URL = "git+https://github.com/lpiccinelli-eth/UniDepth.git"

REPOS = {
    "triposr": ("https://github.com/VAST-AI-Research/TripoSR", "TripoSR", "tsr"),
    "hunyuan3d": (
        "https://github.com/Tencent-Hunyuan/Hunyuan3D-2.1",
        "Hunyuan3D-2.1",
        "hy3dshape",
    ),
}


def installed(package: str) -> str | None:
    try:
        return version(package)
    except PackageNotFoundError:
        return None


def freeze_baseline(path: Path = CONSTRAINTS) -> dict[str, str]:
    """Pin the versions already present, and only those."""
    pins = {name: found for name in BASELINE if (found := installed(name))}
    lines = [
        "# Generated by tools/colab_setup.py - the versions this environment",
        "# already had. Every install is bounded by these so nothing can move a",
        "# package that the rest of the stack is compiled against.",
        *(f"{name}=={found}" for name, found in pins.items()),
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return pins


def pip_install(
    packages: list[str],
    *,
    constraints: Path,
    cache_dir: str | None = None,
    quiet: bool = True,
) -> None:
    command = [
        sys.executable,
        "-m",
        "pip",
        "install",
        # Nothing already satisfied gets touched, which is the other half of
        # keeping the baseline still.
        "--upgrade-strategy",
        "only-if-needed",
        "--constraint",
        str(constraints),
    ]
    if cache_dir:
        command += ["--cache-dir", cache_dir]
    if quiet:
        command.append("-q")
    command += packages

    print("$", " ".join(command[:6]), "...", len(packages), "packages")
    subprocess.run(command, check=True)


def clone(url: str, destination: Path, marker: str) -> str:
    if (destination / marker).is_dir():
        return "already present"
    destination.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "clone", "-q", url, str(destination)], check=True)
    return "cloned"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--backend",
        choices=("both", "triposr", "hunyuan3d", "none"),
        default="both",
        help="Which generation backends to prepare. Default installs both, in one "
        "transaction, because a second transaction later is what causes drift.",
    )
    parser.add_argument(
        "--cache-dir",
        help="pip cache directory. Point it at Drive to make later sessions faster.",
    )
    parser.add_argument(
        "--with-torchmcubes",
        action="store_true",
        help="Compile TripoSR's CUDA marching cubes. Optional: the adapter falls "
        "back to a CPU implementation, so this only buys speed.",
    )
    parser.add_argument(
        "--with-unidepth",
        action="store_true",
        help="Install UniDepth for the 'estimate' scale source, which measures a "
        "photo with no reference object in it. Wide error bars (20%%+); a printed "
        "marker costs one sheet of paper and is several times more accurate.",
    )
    parser.add_argument("--verbose", action="store_true", help="Show all pip output.")
    args = parser.parse_args()

    backends = (
        ("triposr", "hunyuan3d") if args.backend == "both" else ()
    ) or ((args.backend,) if args.backend != "none" else ())

    print("=" * 72)
    print("Freezing the versions this environment already has")
    print("=" * 72)
    before = freeze_baseline()
    for name, found in before.items():
        print(f"  {name:26} {found}")
    print(f"\nwritten to {CONSTRAINTS.relative_to(PROJECT_ROOT)}")

    packages = list(CORE)
    for backend in backends:
        packages += [p for p in BACKEND_PACKAGES[backend] if p not in packages]
    if args.with_unidepth:
        # In the same transaction deliberately: UniDepth's dependencies are the ones
        # most likely to move Pillow, and the constraints file is what stops them.
        packages += [p for p in ("timm", UNIDEPTH_URL) if p not in packages]

    print("\n" + "=" * 72)
    print(f"Installing {len(packages)} packages in one transaction")
    print("=" * 72)
    try:
        pip_install(
            packages,
            constraints=CONSTRAINTS,
            cache_dir=args.cache_dir,
            quiet=not args.verbose,
        )
    except subprocess.CalledProcessError:
        print(
            "\nInstall failed. If pip reports a conflict with a pinned version, that "
            "package genuinely cannot use the baseline: install it on its own and "
            "expect to re-run this script afterwards."
        )
        return 1

    if args.with_torchmcubes:
        print("\nCompiling torchmcubes (optional; a CPU fallback exists)")
        try:
            pip_install(
                ["git+https://github.com/tatsy/torchmcubes.git"],
                constraints=CONSTRAINTS,
                cache_dir=args.cache_dir,
                quiet=not args.verbose,
            )
        except subprocess.CalledProcessError:
            print("  failed to build - TripoSR will use the CPU fallback instead.")

    if backends:
        print("\n" + "=" * 72)
        print("Model source repositories")
        print("=" * 72)
        for backend in backends:
            url, folder, marker = REPOS[backend]
            state = clone(url, PROJECT_ROOT / "third_party" / folder, marker)
            print(f"  {backend:12} {state}")

    print("\n" + "=" * 72)
    print("Did anything move?")
    print("=" * 72)
    moved = {
        name: (found, installed(name))
        for name, found in before.items()
        if installed(name) != found
    }
    for name, (was, now) in moved.items():
        print(f"  {name}: {was} -> {now}")
    if not moved:
        print("  nothing moved - the baseline held")

    print("\n" + "=" * 72)
    if moved:
        print("RESTART THE RUNTIME NOW: Runtime > Restart session")
        print("A package changed underneath the running kernel.")
    else:
        print("Restart the runtime once (Runtime > Restart session), then:")
    print("  !python tools/doctor.py")
    print("=" * 72)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
